# Generated by Django 4.2.11 on 2024-05-03 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disease_detection', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='disease',
            old_name='identification',
            new_name='how_to_identify',
        ),
        migrations.RenameField(
            model_name='disease',
            old_name='prevention',
            new_name='how_to_prevent',
        ),
        migrations.RenameField(
            model_name='disease',
            old_name='treatment',
            new_name='how_to_treat',
        ),
        migrations.AddField(
            model_name='disease',
            name='summary',
            field=models.TextField(null=True),
        ),
        migrations.DeleteModel(
            name='Recommendation',
        ),
    ]
